/* gene-info.js — global gene hover tooltips.
 *
 * A concise description for EVERY gene in the panels, shown as a native `title` (hover)
 * tooltip anywhere a gene appears — dropdown options, the closed <select>, ranking rows,
 * gene-name spans, table cells — kept current as pages render gene lists dynamically.
 *
 * Sources: (a) the project's own slide deck (July 2026) for the ~55 genes it profiles —
 * those carry this dataset's stage dynamics ("here: …", z = zygote, e = early-2-cell,
 * l = late-2-cell) plus function/correlations; (b) general molecular function for the rest.
 * Not every blurb is fully verified (per request, coverage is complete rather than curated);
 * obvious slide slips were corrected to the gene's real function. Extend/adjust via DESC.
 */
window.GeneInfo = (function () {
  "use strict";

  const DESC = {
    // Riken / predicted / poorly-characterized
    "1700013H16Rik": "Poorly-characterized Riken cDNA gene (oocyte/early-embryo-enriched cluster).",
    "1700084M14Rik": "Poorly-characterized Riken cDNA gene (oocyte/testis cluster).",
    "4930451I11Rik": "Poorly-characterized Riken cDNA gene.",
    A430033K04Rik: "Poorly-characterized Riken cDNA gene.",
    D7Ertd443e: "Poorly-characterized genomic locus.",
    Gm11544: "Predicted gene (uncharacterized).",
    Gm11839: "Predicted gene (uncharacterized).",
    Gm14276: "Predicted gene (uncharacterized).",
    Gm14521: "Predicted gene (uncharacterized).",
    Gm15107: "Predicted gene (uncharacterized).",
    Gm1995: "Predicted gene (uncharacterized).",
    Gm4850: "Predicted gene (uncharacterized).",
    Gm6189: "Predicted gene (uncharacterized).",
    Ccdc169: "Coiled-coil-domain protein; poorly characterized.",
    Nhlrc3: "NHL-repeat protein; poorly characterized.",
    Samd10: "Sterile-alpha-motif-domain protein; poorly characterized.",
    Tcp11l2: "T-complex-protein-11-like; poorly characterized.",
    Cdc5lrt1: "Cdc5-like-related transcript; cell-cycle/splicing-associated.",

    // ── maternal-effect / SCMC / oocyte store ──
    Nlrp5: "Subcortical maternal complex (SCMC) core (Mater). Maternally deposited; essential to progress past the 2-cell stage; high in the zygote, then cleared.",
    Padi6: "SCMC component; builds the oocyte cytoplasmic lattices. Maternal; required for ZGA and cleavage — loss arrests at 2-cell.",
    Nlrp2: "SCMC-associated maternal-effect gene; maternal–fetal immune tolerance. Here: steadily decreasing z → e → l.",
    Nlrp9c: "Maternal NLRP of the oocyte store (SCMC-related).",
    Tle6: "Groucho/TLE transcriptional corepressor; part of the subcortical maternal complex. Here: high in e, low in l, high in a few zygotes.",
    Zar1: "Maternal-effect regulator of the oocyte-to-embryo transition. Maternally deposited; loss blocks the 1–2-cell stage.",
    Mos: "Oocyte Mos–MEK–MAPK kinase. Maternal; maintains meiotic (CSF) arrest, cleared after fertilization.",
    Fbxo43: "Emi2 — APC/C inhibitor. Maternal; holds the metaphase-II (CSF) arrest until fertilization.",
    Dnmt1: "Maintenance DNA methyltransferase (oocyte Dnmt1o). Maternal; preserves genomic imprints through cleavage.",
    Uhrf1: "Targets Dnmt1 to hemimethylated DNA; maternal, maintains methylation in early cleavage.",
    Uhrf2: "UHRF2 E3 ligase / methyl-CpG reader; chromatin regulation.",
    Fmn2: "Actin-nucleating formin. Maternal; drives the cytoplasmic actin mesh and off-centre spindle positioning — an asymmetric-division factor.",
    Trim75: "TRIM-family maternal factor that drives minor ZGA. Here: decreasing z → e → l.",
    Btbd18: "Nuclear piRNA-pathway factor; spermatogenesis and transposable-element silencing. Here: rises z → e, falls in l.",
    Zpr1: "ZPR1 zinc-finger factor; cytoplasmic growth signaling, cell-cycle progression and RNA splicing. Here: high in e, low in l, high in a few zygotes.",

    // ── zona pellucida (oocyte / maternal) ──
    Zp1: "Zona pellucida glycoprotein. Oocyte-made (maternal); part of the sperm-binding coat; declines after fertilization.",
    Zp2: "Zona pellucida secondary sperm receptor that firmly anchors the sperm. Oocyte-made (maternal). Here: high in z/e, lower in l; correlates with Rbm8a.",
    Zp3: "Zona pellucida glycoprotein / primary sperm receptor. Oocyte-made (maternal); declines after fertilization.",

    // ── zygotic genome activation / totipotency ──
    Duxf1: "Dux family — a master ZGA activator; transiently switches on the minor-ZGA / MERVL 2-cell program, then is silenced.",
    Duxf3: "Dux family — a master ZGA activator; transiently induces the 2-cell / MERVL program at genome activation.",
    Zscan4a: "2-cell / '2C-like' totipotency marker; transient at ZGA (telomere/genome stability).",
    Zscan4b: "2-cell / '2C-like' marker; maintains genomic stability and DNA demethylation. Here: similar across all stages.",
    Zscan4d: "2-cell / '2C-like' totipotency marker; transient at ZGA (telomere/genome stability).",
    Zscan4e: "2-cell / '2C-like' totipotency marker; transient at ZGA (telomere/genome stability).",
    Zscan4f: "2-cell / '2C-like' totipotency marker; transient at ZGA (telomere/genome stability).",
    Obox1: "Oocyte-specific homeobox TF; activates zygotic genome activation genes.",
    Obox2: "Oocyte-specific homeobox TF; drives ZGA. In this panel's TGF-β/RNA-processing anchor cluster.",
    Obox3: "Oocyte-specific homeobox TF; activates ZGA genes.",
    Obox8: "Oocyte-specific homeobox TF; drives zygotic genome activation.",
    "MuERV-L": "MERVL endogenous retrovirus — the definitive 2-cell / totipotency marker. Here: high in e/l (a hub other 2-cell genes correlate with).",
    L1td1: "LINE-1-associated RNA-binding protein; totipotent 2-cell program and pluripotency.",
    Zfp352: "2-cell-specific ZGA gene and Dux target.",
    Nr5a2: "Nuclear receptor (LRH-1) that helps trigger zygotic genome activation.",
    Gadd45a: "Stress-responsive protein: cell-cycle arrest, DNA repair, apoptosis and epigenetic DNA demethylation. Here: rises z → e, level in l.",
    Kdm4dl: "KDM4/JmjC-family histone demethylase. Here: low in z, high in e, low in l.",
    Eif1ad12: "Translation-factor-like protein in the ZGA-linked gene cluster.",
    Trib3: "Pseudokinase stress sensor; likely activated after ZGA. Here: low in z, higher in e/l.",
    LincGET: "2-cell nuclear lncRNA that recruits CARM1; its ASYMMETRY between blastomeres biases the first lineage decision toward the inner (pluripotent) fate.",
    Carm1: "Arginine methyltransferase (H3R26me2); mRNA processing and signaling. Higher CARM1 in a 2–4-cell blastomere biases its progeny toward inner-cell-mass fate. Here: high in z, decreasing in e/l; correlates with MuERV-L, Yap1, Rbm8a.",
    Pqbp1: "Polyglutamine-binding protein; pre-mRNA splicing and transcription — ZGA-related. Here: high in l, low in z/e.",

    // ── pluripotency / ICM–TE–endoderm fate ──
    Sox2: "Pluripotency transcription factor; the first TF to mark inner-cell-mass fate. Early Sox2 heterogeneity between blastomeres foreshadows ICM vs trophectoderm.",
    Klf2: "Naive-pluripotency transcription factor of the inner cell mass.",
    Klf4: "Naive-pluripotency transcription factor (inner cell mass / epiblast).",
    Klf6: "Differentiation-linked KLF transcription factor.",
    Esrrb: "Transcription factor for stem-cell pluripotency and placental development. Here: similar across all stages.",
    Tfcp2l1: "Naive-pluripotency transcription factor.",
    Foxd3: "Pluripotency / inner-cell-mass transcription factor.",
    Lin28a: "RNA-binding pluripotency factor (blocks let-7 miRNA maturation); translational and epigenetic regulation. Here: high in z/e, lower in l; correlates with Rbm8a, Nup62cl.",
    Myc: "Master proto-oncogene transcription factor; proliferation/biosynthesis; part of the CARM1–Myc axis biasing cells toward ICM. Here: slight rise z → e → l.",
    Bmyc: "Brain-expressed Myc-like protein; modulates Myc activity.",
    Yap1: "Hippo-pathway transcriptional coactivator. Nuclear YAP in outer cells switches on trophectoderm genes; its inside–outside asymmetry drives TE-vs-ICM. Here: high in z → low e → lowest l; correlates with MuERV-L.",
    Tead2: "TEAD transcription factor; partners YAP to specify trophectoderm.",
    Lats1: "Hippo kinase, active in inner cells; excludes YAP from the nucleus, favouring inner-cell-mass fate.",
    Gata2: "GATA transcription factor (hematopoietic / trophoblast lineages).",
    Gata3: "Trophectoderm transcription factor downstream of TEAD4/YAP.",
    Gata4: "Primitive-endoderm transcription factor (later inner-cell-mass segregation).",
    Sox7: "Primitive-endoderm transcription factor / marker.",
    Hand1: "Trophoblast-giant-cell transcription factor.",
    Gcm1: "Glial-cells-missing-1 transcription factor; placental syncytiotrophoblast.",
    Ets2: "ETS transcription factor; trophoblast development and RAS-responsive transcription.",
    Elf3: "Epithelial ETS transcription factor associated with trophectoderm.",
    Elf1: "ETS-family transcription factor.",
    Tfap2a: "AP-2 transcription factor; epithelial / trophectoderm programs.",
    Id1: "BMP-target HLH factor that biases cells away from the pluripotent program.",
    Id4: "BMP-target HLH factor; differentiation-associated.",
    Cebpa: "C/EBPα differentiation transcription factor.",
    Cebpb: "C/EBPβ differentiation transcription factor.",
    Tcf7: "Wnt/β-catenin transcription factor (TCF1).",
    Lifr: "LIF receptor; JAK/STAT3 signaling that supports pluripotency.",

    // ── polarity / junctions / compaction / cleavage cytoskeleton ──
    Pard3: "Apical polarity scaffold; organizes tight junctions. From the 8-cell stage it establishes apical–basal polarity and inside–outside fate. Earlier asymmetry may indicate stronger or earlier polarity in some blastomeres.",
    Pard6a: "Par-complex polarity adaptor (with aPKC); apical-domain formation at polarization.",
    Prkci: "Atypical PKC (aPKC) — polarity kinase of the Par complex; cell polarity, survival and proliferation; interacts with PARD6, promotes mTOR. Here: high in z/e, lower in l.",
    Prkce: "Protein kinase C-epsilon; PKC signalling in the early embryo.",
    Ctnnb1: "β-catenin — E-cadherin adhesion at compaction plus Wnt signalling; adhesion differences influence cell positioning.",
    Cdc42: "Rho-family GTPase that builds the apical domain during polarization. In this panel's developmental-regulation anchor cluster.",
    RhoA: "Rho GTPase controlling actomyosin contractility for cleavage and compaction.",
    Rhou: "Atypical Rho GTPase (Wrch1) acting on junctions and actin.",
    Rras: "R-Ras small GTPase; cell adhesion and growth signalling.",
    Rras2: "Ras-family small GTPase (TC21); growth/proliferation signalling. Here: high in some zygotes, lowest in l.",
    Myh9: "Non-muscle myosin IIA; cortical tension for compaction and apical-domain positioning.",
    Fmnl2: "Formin-family actin regulator (motility and junctions).",
    Arpc1b: "Arp2/3-complex subunit; branched cortical actin networks.",
    Gsn: "Gelsolin; calcium-dependent actin severing and capping.",
    Nhsl1: "NHS-like actin regulator (WAVE/SCAR pathway).",
    Numb: "Cell-fate determinant that can segregate asymmetrically at division and inhibits Notch.",
    Krt8: "Keratin-8 intermediate filament; early trophectoderm epithelial marker (TROMA-1).",
    Krt18: "Keratin-18 intermediate filament; trophectoderm epithelial marker.",
    Krt12: "Keratin-12 intermediate filament (epithelial).",
    Dsg2: "Desmoglein-2 desmosomal junction protein; trophectoderm epithelialization.",
    Pkp2: "Plakophilin-2 desmosomal protein; epithelial junctions.",
    Gja4: "Connexin gap-junction protein; intercellular coupling during compaction.",
    Gjb5: "Connexin gap-junction protein; intercellular coupling.",
    Cdh8: "Cadherin-8; calcium-dependent cell–cell adhesion.",
    Itgb3: "Integrin β3 — cell-surface receptor mediating adhesion and signalling. Here: high in some zygotes → lower e → lowest l.",
    Sdc4: "Syndecan-4 adhesion / signalling co-receptor.",
    Specc1l: "Cytoskeletal cross-linker supporting adhesion and junction integrity.",
    Ninj2: "Ninjurin-2 adhesion molecule.",
    Ceacam10: "CEA-family cell-adhesion glycoprotein.",
    Muc15: "Membrane-anchored mucin (cell-surface glycoprotein).",
    Pkd1: "Polycystin-1; mechanosensory adhesion/signalling receptor.",
    Prom1: "Prominin-1 / CD133; apical-membrane glycoprotein and stem-cell marker.",

    // ── microtubules / spindle / cilia / motors ──
    Clip2: "CLIP-115 microtubule +TIP protein; regulates the cytoskeleton. Here: high in z, lower in e/l.",
    Katnal2: "Katanin-like microtubule-severing ATPase.",
    Kifc2: "Kinesin-C motor; minus-end microtubule transport.",
    Map7d1: "MAP7-domain microtubule-associated protein; stabilizes microtubules.",
    Tppp3: "Tubulin-polymerization-promoting protein.",
    Fam83d: "FAM83D; mitotic-spindle regulator.",
    Fam110c: "FAM110C; microtubule organization, cell migration and cell-cycle progression. Here: keeps decreasing z → e → l.",
    Mitd1: "MIT-domain protein; ESCRT-linked cytokinetic abscission.",
    Hook1: "Microtubule-tethering adaptor (endosomes / spermatid manchette).",
    Dnal4: "Dynein axonemal light chain; cilia / flagella motility.",
    Myo5a: "Myosin-Va actin motor; organelle/vesicle transport.",
    Myo5b: "Myosin-Vb actin motor; recycling-endosome transport.",
    Myo7a: "Myosin-VIIa actin motor (stereocilia / adhesion).",
    Pgm5: "Phosphoglucomutase-5 (aciculin); cytoskeletal adaptor, catalytically dead.",

    // ── signalling: Wnt · Notch · Nodal/TGF-β/BMP · FGF · Hedgehog · RTK ──
    Fzd2: "Frizzled Wnt receptor.",
    Fzd4: "Frizzled Wnt receptor.",
    Fzd5: "Frizzled Wnt receptor. Here: rises z → e, decreases in l.",
    Axin2: "Wnt/β-catenin target and negative-feedback scaffold — a readout of pathway activity.",
    Wif1: "Secreted Wnt inhibitor.",
    Wnt7b: "Wnt ligand.",
    Nrarp: "Notch target that also tunes Wnt — a signalling-feedback node.",
    Zbed3: "Axin-binding Wnt-pathway activator.",
    Notch2: "Notch receptor; Notch signalling is active in the trophectoderm lineage.",
    Notch3: "Notch receptor.",
    Jag2: "Jagged-2, a membrane-bound Notch ligand. Here: similar in z/e, lower in l; correlates with Usp54, Clip2 (strongly), Itgb3, Zp2, Calu.",
    Dtx2: "Deltex-2, a Notch-pathway regulator.",
    Hes1: "Notch-target bHLH transcriptional repressor.",
    Nodal: "Nodal (TGF-β/Activin) ligand; establishes embryonic axes and pluripotency signalling.",
    Lefty2: "Nodal antagonist; shapes Nodal signalling gradients.",
    Smad1: "BMP-branch SMAD effector; transduces BMP signals. Here: high in e, same in z, low in l (likely maternally inherited, depleting by late-2-cell).",
    Smad2: "Nodal/Activin-branch SMAD effector.",
    Smad7: "Inhibitory SMAD; negative feedback on TGF-β/BMP.",
    Skil: "SnoN/SKIL; SMAD corepressor antagonizing TGF-β signalling.",
    Bmp5: "BMP ligand; promotes differentiation programs.",
    Bmp7: "BMP ligand; promotes differentiation / trophoblast programs.",
    Bmpr1b: "BMP type-I receptor.",
    Acvr2b: "Activin/Nodal type-II receptor.",
    Amhr2: "TGF-β-superfamily (AMH) type-II receptor.",
    Bambi: "BMP/TGF-β pseudoreceptor (decoy) that dampens signalling.",
    Inha: "Inhibin subunit; antagonizes activin signalling.",
    Fst: "Follistatin; binds and inhibits activin/BMP.",
    Fkbp1a: "FKBP12; keeps TGF-β-family receptors inactive until ligand binds.",
    Ltbp1: "Latent-TGF-β-binding protein; stores/presents TGF-β in the matrix.",
    Tgfb1: "TGF-β ligand.",
    Tgfb2: "TGF-β ligand.",
    Eid2: "EID2 — binds SMAD and negatively regulates transcription (represses acetyltransferases). Here: rises z → e → l; correlates with MuERV-L, Zscan4d, Usp54.",
    Eid2b: "EID-family transcriptional repressor (differentiation inhibitor).",
    Fgf4: "The key ICM-derived FGF; drives primitive-endoderm vs epiblast segregation; involved in cell proliferation. Here: rises z → e → l (differs p1 vs p2); correlates with Fgf8.",
    Fgf8: "Secreted FGF receptor-ligand (patterning). Here: high in z, lower in e/l.",
    Egfr: "EGF receptor; growth-factor signalling and fate regulation.",
    Nrg2: "Neuregulin-2; ErbB-receptor ligand.",
    Ntf3: "Neurotrophin-3; Trk-receptor ligand.",
    Raf1: "RAF1 kinase of the RAS–MAPK cascade; cell signalling and fate.",
    Stat6: "STAT6 transcription factor; cytokine (IL-4/IL-13) signalling and fate regulation.",
    Shc2: "SHC adaptor; couples receptor tyrosine kinases to RAS/MAPK.",
    Shc3: "SHC adaptor; RTK–RAS/MAPK signalling (neural).",
    Gli3: "Hedgehog-pathway transcription factor (repressor/activator).",
    Gpr161: "Ciliary GPCR that negatively regulates Hedgehog signalling.",
    Tulp3: "Ciliary trafficking factor; negative regulator of Hedgehog.",
    Nrp1: "Neuropilin-1 co-receptor (VEGF / semaphorin signalling).",
    Plxnc1: "Plexin-C1 semaphorin receptor (guidance signalling).",
    Sema6c: "Semaphorin-6C; transmembrane guidance cue.",
    Lpar6: "Lysophosphatidic-acid receptor 6; lipid-GPCR signalling.",
    Adcy2: "Adenylate cyclase 2; synthesizes cAMP (GPCR signalling).",
    Gnb4: "Heterotrimeric G-protein β4 subunit.",
    Gng3: "Heterotrimeric G-protein γ3 subunit.",
    Gpsm1: "G-protein signalling modulator (AGS3); spindle orientation and GPCR signalling.",
    Rgs17: "Regulator of G-protein signalling; GTPase-accelerating protein.",
    Rinl: "Ras-interaction/Rab-GEF; endosomal signalling.",
    Rasl11b: "Ras-like GTPase; positive regulator of rRNA transcription.",
    Tcl1b2: "TCL1-family AKT co-activator; oocyte-enriched, maternal.",
    Tcl1b3: "TCL1-family co-activator; enhances AKT phosphorylation/activation. Here: rises z → e, decreases in l; correlates with Jag2.",
    Tcl1b4: "TCL1-family AKT co-activator; oocyte-enriched, maternal.",
    Mtor: "mTOR kinase; nutrient/growth signalling and translational control.",
    Foxo1: "FOXO1 forkhead transcription factor; metabolism, stress and quiescence.",
    Dusp5: "Dual-specificity phosphatase; inactivates ERK MAP-kinase.",
    Dusp7: "Dual-specificity phosphatase; inactivates ERK MAP-kinase.",
    Egr1: "EGR1 immediate-early zinc-finger transcription factor.",
    Pthlh: "Parathyroid-hormone-related peptide; developmental signalling.",
    Adm2: "Adrenomedullin-2; secreted peptide hormone (vasoactive signalling).",
    Gnrh1: "Gonadotropin-releasing hormone (neuroendocrine).",
    Nppb: "B-type natriuretic peptide; secreted hormone.",
    C2cd4a: "C2-calcium-dependent-domain protein; nuclear signalling response.",
    Stac2: "SH3/cysteine-rich adaptor; voltage-gated calcium-channel regulator.",
    Stim2: "ER calcium sensor; drives store-operated calcium entry.",
    Ppef1: "Serine/threonine protein phosphatase with EF-hands (calcium-regulated).",

    // ── chromatin / transcription / RNA processing ──
    Setd2: "H3K36me3 methyltransferase; transcription-coupled chromatin mark.",
    Ep300: "p300 histone acetyltransferase; enhancer activation, including at ZGA.",
    Brd4: "BET bromodomain reader; releases paused Pol II and helps drive zygotic genome activation.",
    Brd1: "Bromodomain protein; subunit of a histone-acetyltransferase (MOZ/MORF) complex.",
    Brdt: "Testis bromodomain protein that remodels sperm chromatin — a paternal-lineage marker.",
    Chd8: "ATP-dependent chromatin remodeler.",
    Mta2: "NuRD-complex subunit (repressive chromatin remodeling).",
    Actr5: "Actin-related protein of the INO80 chromatin-remodeling complex; regulates chromatin accessibility. Here: rises z → e, level in l.",
    Trim66: "TRIM/bromodomain chromatin reader (spermatid; transcriptional repression).",
    Rbp7: "Cellular retinol-binding protein (retinoid transport). Here: slightly lower in e, not significantly different.",
    Nono: "Paraspeckle RNA-binding protein; splicing and nuclear RNA retention.",
    Dpy30: "COMPASS/MLL H3K4-methylation subunit.",
    Ddx20: "DEAD-box RNA helicase (SMN/Gemin complex; snRNP assembly).",
    Ddx43: "Germ-cell DEAD-box RNA helicase (HAGE).",
    Rbm8a: "Exon-junction-complex core (Y14); mRNA transport, translation and decay. Here: slight rise z → e → l; correlates with MuERV-L, Pqbp1, Yap1 (e) and Nup62cl (l).",
    Raly: "hnRNP-C-related RNA-binding protein; mRNA processing and transcriptional control. Here: high in e, lower in z, lowest in l; correlates with MuERV-L, Ddb1, Nup62cl (e).",
    Snrpd3: "Sm-core snRNP protein; spliceosome.",
    Phf5a: "Spliceosome component (SF3b).",
    Sf1: "Splicing factor 1; branch-point recognition in pre-mRNA splicing. Here: high in some zygotes, little change across e/l.",
    Tsen54: "tRNA-splicing endonuclease subunit.",
    Exosc6: "RNA exosome ribonuclease subunit; RNA processing and decay. Here: rises z → e, level in l.",
    Dcps: "Scavenger mRNA-decapping enzyme; RNA turnover.",
    Tardbp: "TDP-43 RNA-binding protein (splicing / RNA stability).",
    Fmr1: "FMRP translational regulator (RNA binding).",
    Msi2: "Musashi-2 RNA-binding translational regulator.",
    Cdv3: "CDV3; ribosome-associated, translation-linked protein.",
    Zfp622: "Zinc-finger protein; ribosome-biogenesis-associated (Zpr1-binding).",
    Rps13: "40S ribosomal protein S13; translation.",
    Srp54: "Signal-recognition-particle 54 GTPase; co-translational ER targeting.",
    Srp72: "Signal-recognition-particle 72 subunit; ER targeting.",
    Ptrh1: "Peptidyl-tRNA hydrolase; translational quality control.",
    Taf9b: "TBP-associated factor (TFIID); general transcription.",
    Nfya: "NF-Y CCAAT-box transcription-factor subunit.",
    Tfdp1: "DP1 — E2F dimerization partner; drives cell-cycle S-phase entry.",
    Cdkn2c: "INK4 CDK inhibitor (p18); cell-cycle brake.",
    Nr1d1: "Rev-erbα nuclear receptor; circadian and metabolic transcriptional repressor.",
    Clock: "CLOCK bHLH-PAS circadian transcription factor.",
    Mlxipl: "ChREBP glucose-responsive transcription factor (carbohydrate metabolism). Here: high in z, low in e, active again in l.",
    Trps1: "GATA-type transcriptional repressor.",
    Tle3: "Groucho/TLE transcriptional corepressor.",
    Zfp54: "KRAB zinc-finger transcription factor.",
    Ripply2: "Transcriptional corepressor (somite segmentation).",
    Wac: "WW-domain adaptor; transcription elongation and autophagy.",
    Obi1: "RNF219; origin-binding E3 ligase regulating DNA-replication licensing.",
    Rnaseh2b: "RNase H2 subunit; removes ribonucleotides from DNA (genome stability).",
    Pin1: "Peptidyl-prolyl isomerase (pSer/Thr-Pro); cell-cycle and signalling control.",

    // ── homeobox / lineage transcription factors (later programs) ──
    Arx: "Aristaless-related homeobox transcription factor (neural/endocrine).",
    Otx1: "Anterior/head-patterning homeobox transcription factor.",
    Pax6: "Paired-box transcription factor (eye/brain/pancreas).",
    Msx1: "Msh homeobox transcription factor; developmental patterning.",
    Hesx1: "Homeobox transcription factor (forebrain/pituitary).",
    Hhex: "Hematopoietically-expressed homeobox TF (endoderm).",
    Pknox2: "PBX/knotted TALE-class homeobox transcription factor.",
    Tbx19: "T-box transcription factor (pituitary).",
    Lhx8: "Oocyte-specific LIM-homeobox transcription factor (maternal).",
    Esx1: "X-linked homeobox transcription factor (placenta / germ cell).",

    // ── germ-cell / sperm / paternal ──
    Nanos2: "Germ-cell RNA-binding fate determinant.",
    Fthl17f: "Ferritin-heavy-like X-linked gene enriched with the paternal pronucleus.",
    Hspa2: "Testis HSP70 chaperone; protein folding and regulated degradation. Here: low in z, high in e, low in l; correlates with Rbp7.",
    Spz1: "Testis bHLH-Zip transcription factor.",
    Uba1y: "Y-linked ubiquitin-activating enzyme.",
    Tmem81: "Sperm transmembrane protein; sperm–egg fusion at fertilization.",
    Xlr: "X-linked lymphocyte-regulated / SYCP3-like protein (germ cell / meiosis).",
    Xlr5b: "X-linked lymphocyte-regulated / SYCP3-like protein (germ cell).",
    Prl8a2: "Prolactin-family hormone (decidual).",

    // ── metabolism / mitochondria / redox ──
    Ldhb: "Lactate dehydrogenase B; glycolysis / cellular energy metabolism.",
    Cox7b: "Cytochrome-c-oxidase subunit VIIb; mitochondrial energy metabolism. Here: about the same in z/e, lower in l.",
    Ndufb7: "Mitochondrial complex-I subunit (oxidative phosphorylation).",
    Uqcc6: "Mitochondrial respiratory-complex assembly factor.",
    Vdac2: "Voltage-dependent anion channel; mitochondrial metabolite exchange and apoptosis. In this panel's TGF-β/metabolism anchor cluster.",
    Vdac3: "Voltage-dependent anion channel; mitochondrial outer-membrane transport.",
    Immt: "Mitofilin/MIC60; mitochondrial cristae organization (MICOS).",
    Apoo: "Apolipoprotein-O / MICOS subunit; mitochondrial cristae.",
    Gdap1: "Ganglioside-induced differentiation protein; mitochondrial dynamics. Here: high in some zygotes → lower e → lowest l.",
    Mrps5: "Mitochondrial ribosomal protein S5; mitochondrial translation.",
    Hspe1: "HSP10 mitochondrial co-chaperonin.",
    Txnrd2: "Thioredoxin reductase 2; mitochondrial redox (selenoprotein).",
    Glrx: "Glutaredoxin; thiol/redox regulation.",
    Hint2: "Mitochondrial histidine-triad nucleotide hydrolase.",
    Pdha2: "Pyruvate dehydrogenase E1α (testis); pyruvate → acetyl-CoA.",
    Mcat: "Malonyl-CoA-ACP transacylase; mitochondrial fatty-acid synthesis.",
    Aldh2: "Mitochondrial aldehyde dehydrogenase; acetaldehyde/alcohol metabolism. Here: high in z/e, lower in l.",
    Hk2: "Hexokinase-2; first committed step of glycolysis.",
    Pgk1: "Phosphoglycerate kinase 1; glycolytic ATP generation.",
    G6pdx: "Glucose-6-phosphate dehydrogenase; pentose-phosphate pathway (NADPH).",
    Gapdh: "Glyceraldehyde-3-phosphate dehydrogenase; glycolysis (housekeeping).",
    Car2: "Carbonic anhydrase II; CO2/bicarbonate and pH regulation.",
    Galk1: "Galactokinase; galactose metabolism.",
    Ampd3: "AMP deaminase 3; purine/energy metabolism.",
    Arg2: "Arginase-2; mitochondrial arginine → ornithine.",
    Smox: "Spermine oxidase; polyamine catabolism.",
    Akr1b8: "Aldo-keto reductase; aldehyde/sugar reduction.",
    Akr1c21: "Aldo-keto reductase; steroid/prostaglandin metabolism.",
    Scd2: "Stearoyl-CoA desaturase-2; monounsaturated-fatty-acid synthesis.",
    Elovl7: "Fatty-acid elongase; very-long-chain fatty-acid synthesis.",
    Mgll: "Monoacylglycerol lipase; endocannabinoid / lipid signalling.",
    Dbi: "Diazepam-binding inhibitor / acyl-CoA-binding protein; lipid metabolism.",
    Pcyt1b: "CTP:phosphocholine cytidylyltransferase; phosphatidylcholine synthesis.",
    Ppcs: "Phosphopantothenoylcysteine synthetase; coenzyme-A biosynthesis.",
    Gsta2: "Glutathione S-transferase; detoxification / redox.",
    Gsta4: "Glutathione S-transferase; detoxification / redox.",
    Gstm5: "Glutathione S-transferase mu; detoxification. In this panel's developmental-regulation anchor cluster.",
    Mt1: "Metallothionein-1; metal binding and oxidative-stress buffering.",
    Upp1: "Uridine phosphorylase; pyrimidine salvage.",
    Slc2a1: "GLUT1 glucose transporter. Here: slight rise z → e, decrease in l.",
    Slc38a2: "Sodium-coupled neutral amino-acid transporter (SNAT2).",
    Slc19a3: "Thiamine transporter.",
    Slc20a1: "Sodium-phosphate cotransporter (PiT1).",
    Slc39a8: "ZIP8 zinc/manganese transporter.",
    Slc66a1: "Lysosomal amino-acid transporter (PQLC2).",
    Atp1b2: "Na+/K+-ATPase β2 subunit; ion transport. Here: detected essentially only in late-2-cell.",
    Npc1l1: "Niemann-Pick-C1-like-1; intestinal cholesterol uptake transporter.",
    Cubn: "Cubilin; endocytic receptor for nutrient uptake.",
    Lrp2: "Megalin (LRP2); multiligand endocytic receptor.",
    Lrp1b: "LDL-receptor-related protein 1B; endocytic receptor.",

    // ── protein quality control / trafficking / secretion ──
    Psmb7: "Proteasome β-subunit; trypsin-like proteolysis and protein degradation. Here: similar in z/l, decreased in e; correlates with Pard3.",
    Psme3: "Proteasome activator PA28γ; ubiquitin-independent protein turnover. Here: high in z/e, lower in l; correlates with Usp54.",
    Usp54: "Deubiquitinating-enzyme-family protein (catalytically inactive USP). Here: same in z/e, lower in l; strongly correlates with Ddb1.",
    Usp7: "USP7/HAUSP deubiquitinase; regulates p53/MDM2 and chromatin factors.",
    Ubr7: "UBR-box E3 ubiquitin ligase (N-end-rule pathway).",
    Rnf128: "GRAIL E3 ubiquitin ligase; immune tolerance.",
    Trim38: "TRIM E3 ubiquitin ligase (innate immunity).",
    Ddb1: "DNA-damage-binding protein / CUL4 E3-ligase adaptor; DNA repair and protein degradation. Here: high in z/e, low in l; correlates with Nup62cl (e).",
    Faf1: "Fas-associated factor 1; apoptosis and proteostasis (ubiquitin-linked).",
    Atg4d: "Autophagy cysteine protease; processes ATG8/LC3.",
    Bag3: "BAG3 co-chaperone (HSP70); selective autophagy and proteostasis.",
    Hspa5: "BiP/GRP78 — ER HSP70 chaperone; unfolded-protein response.",
    Hspb8: "Small heat-shock protein; chaperone / autophagy.",
    Dnaja4: "HSP40 (DnaJ) co-chaperone; protein folding.",
    Xbp1: "XBP1; unfolded-protein-response transcription factor (ER stress, secretion).",
    Ormdl3: "ER transmembrane protein; sphingolipid-synthesis regulation. Here: near-zero in z/l, high in e; correlates with Hspa2.",
    Mogs: "Mannosyl-oligosaccharide glucosidase; N-linked glycosylation.",
    Pgap1: "GPI-anchor remodeling (post-GPI deacylase).",
    Tmed6: "p24/TMED cargo-transport protein; secretory trafficking.",
    Nsf: "NSF AAA-ATPase; SNARE recycling for vesicle fusion.",
    Sec1: "Munc18/Sec1 SNARE regulator; vesicle fusion.",
    Exoc8: "Exocyst-complex subunit; vesicle tethering at the membrane.",
    Vps4a: "VPS4 AAA-ATPase; disassembles ESCRT filaments (abscission, budding).",
    Rab9: "Rab9 GTPase; endosome-to-Golgi transport.",
    Arl4d: "ADP-ribosylation-factor-like GTPase; membrane trafficking.",
    Sytl4: "Synaptotagmin-like 4; Rab effector in regulated secretion.",
    Unc13c: "Munc13; presynaptic vesicle priming.",
    Erc2: "Presynaptic active-zone scaffold (ELKS/CAST family).",
    Pheta1: "FAM109A EH-domain endosomal adaptor.",
    Pi4k2b: "Phosphatidylinositol-4-kinase-2β; PI signalling and membrane trafficking.",
    Nup153: "Nuclear-pore-complex protein; nucleocytoplasmic transport.",
    Nup62cl: "Nucleoporin-62-like; protein and nucleocytoplasmic transport. Here: high in z → low e → lowest l (always depleting); correlates with MuERV-L (e).",
    Tmem37: "Transmembrane protein; voltage-gated-calcium-channel γ-like subunit.",
    Tmem108: "Transmembrane protein (neuronal development).",
    Tmed6: "p24/TMED family cargo receptor; ER-to-Golgi transport.",

    // ── apoptosis / stress / immune ──
    Casp8: "Caspase-8; death-receptor apoptosis initiator protease.",
    Pmaip1: "NOXA; BH3-only pro-apoptotic protein.",
    Tnfaip8: "TNFAIP8; anti-apoptotic / autophagy modulator.",
    Pawr: "PAR-4; pro-apoptotic leucine-zipper protein.",
    Serpinb9b: "Serpin; intracellular protease (granzyme-B) inhibitor.",
    Mx1: "Interferon-induced GTPase; antiviral effector.",
    Oas1h: "2'-5'-oligoadenylate synthetase-like; antiviral RNA sensor.",
    Ifi35: "Interferon-induced protein 35; innate-immune signalling.",
    Irf1: "Interferon-regulatory-factor-1 transcription factor (immune).",
    Aim2: "AIM2 inflammasome cytosolic DNA sensor (innate immunity).",
    Cd1d1: "CD1d; lipid-antigen presentation molecule (immune).",
    Cd68: "CD68 macrophage scavenger/lysosomal glycoprotein (immune).",
    Cd7: "CD7 T/NK-cell surface glycoprotein (immune).",
    Ms4a1: "CD20 B-cell surface protein (immune).",
    Fcgr1: "Fc-gamma receptor I (CD64; immune).",
    Ighg3: "Immunoglobulin heavy constant gamma-3 (antibody; immune).",
    Il1a: "Interleukin-1α; inflammatory cytokine.",
    Il31: "Interleukin-31; immune cytokine.",
    Cst3: "Cystatin C; secreted cysteine-protease inhibitor.",
    Cst7: "Cystatin F; cysteine-protease inhibitor (immune).",
    Entpd1: "CD39 ectonucleotidase; purinergic signalling.",

    // ── other enzymes / structural / miscellany ──
    Parp12: "PARP-family mono-ADP-ribosyltransferase (interferon/stress response).",
    Ppp2cb: "Protein phosphatase 2A catalytic β; major Ser/Thr phosphatase.",
    Ppp1r8: "Protein-phosphatase-1 regulatory subunit (NIPP1); RNA processing and cell proliferation. Here: slight rise z → e, drop e → l; correlates with Rbm8a.",
    Mtmr14: "Myotubularin-related phosphatase (jumpy); dephosphorylation linked to metabolism/autophagy. Here: decreases z → e → l.",
    Calu: "Calumenin; ER calcium-binding protein. Here: mild decrease z → e → l.",
    Guca1a: "Guanylate-cyclase-activating protein; calcium-binding regulator. Here: slight rise z → e, drop in l; correlates with Rbm8a, Calu.",
    Calm5: "Calmodulin-like 5; calcium sensor.",
    Pcp4: "Purkinje-cell protein-4; calmodulin regulator.",
    Sparc: "Osteonectin (SPARC); matricellular ECM glycoprotein.",
    Spp1: "Osteopontin (SPP1); secreted adhesion/signalling phosphoprotein.",
    Lama1: "Laminin α1; basement-membrane ECM (primitive endoderm).",
    Pxdn: "Peroxidasin; extracellular-matrix crosslinking (basement membrane).",
    Plat: "Tissue plasminogen activator; fibrinolytic serine protease.",
    Cpa1: "Carboxypeptidase A1; digestive metallo-protease.",
    Enpep: "Aminopeptidase A (glutamyl); peptidase (angiotensin processing).",
    Tpp1: "Lysosomal tripeptidyl-peptidase 1.",
    Ptges: "Prostaglandin-E synthase; eicosanoid signalling.",
    Duoxa2: "Dual-oxidase maturation factor; thyroid H2O2 generation.",
    Bglap: "Osteocalcin (bone Gla protein).",
    Bglap2: "Osteocalcin-related bone Gla protein.",
    Psg26: "Pregnancy-specific glycoprotein (placental).",
    Maged2: "MAGE-family adaptor (renal salt handling; apoptosis regulation).",
    Bex1: "Brain-expressed X-linked 1; signalling adaptor.",
    Impact: "IMPACT; translation regulator (inhibits GCN2), imprinted.",
    Cdv3: "CDV3; translation-associated protein.",
    Fhl2: "Four-and-a-half LIM-domain 2; scaffold / transcriptional co-regulator.",
    Fhl5: "Four-and-a-half LIM-domain 5; CREM co-activator (spermatogenesis).",
    Tes: "Testin; LIM-domain focal-adhesion protein.",
    Inka1: "INKA1; PAK4 inhibitor (cytoskeleton / neural crest).",
    Rasl11b: "Ras-like GTPase; rRNA-transcription regulator.",
    Sox21: "SoxB2 transcriptional repressor.",
    Sox4: "SoxC transcription factor; progenitor / differentiation.",
    Sox6: "SoxD transcription factor; differentiation.",
    Apoa1: "Apolipoprotein A-I; HDL lipid transport.",
    Apom: "Apolipoprotein M; lipid (S1P) transport.",
    Apol7b: "Apolipoprotein-L family. Here: detected essentially only in late-2-cell.",
    Rbp7: "Cellular retinol-binding protein (retinoid transport). Here: slightly lower in e, not significantly different across stages.",
    Cdc42: "Rho-family GTPase; builds the apical domain during polarization.",
    Pgm5: "Aciculin (phosphoglucomutase-5-like); cytoskeletal adaptor.",
    Dnal4: "Dynein axonemal light chain; ciliary/flagellar motility.",
    Myorg: "Myogenesis-regulating glycosidase.",
    Mymx: "Myomixer/Myomerger; cell-fusion micropeptide.",
    Spata7: "Spermatogenesis-associated 7; ciliary protein (retina/germ line).",
    Elovl7: "Very-long-chain fatty-acid elongase.",
    Gng3: "G-protein γ3 subunit; heterotrimeric-G signalling.",
    Dynap: "Dynactin-associated protein.",
    Taar2: "Trace-amine-associated receptor; GPCR.",
    Unc79: "UNC79; NALCN sodium-leak-channel-complex subunit.",
    Hspe1: "HSP10 mitochondrial co-chaperonin.",
    Tmem37: "Transmembrane calcium-channel γ-like subunit.",
    Slc39a8: "ZIP8 divalent-metal (Zn/Mn) transporter.",
    Rgs17: "Regulator of G-protein signalling; GAP for Gα.",
    Rasl11b: "Ras-like GTPase; positive regulator of rRNA transcription.",
    Nono: "Paraspeckle DBHS RNA-binding protein; splicing/retention.",
    Trnp1: "TRNP1 nuclear DNA-associated protein; controls cell-population proliferation. Here: decreasing z → e → l; correlates with Jag2.",
    Camk2d: "Ca2+/calmodulin-dependent protein kinase II delta; calcium signal transduction.",
    Ppic: "Cyclophilin C; peptidyl-prolyl isomerase (protein folding).",
    Psen1: "Presenilin-1; catalytic subunit of γ-secretase (cleaves Notch and others).",
    Psen2: "Presenilin-2; γ-secretase catalytic subunit (Notch processing).",
  };

  const desc = (g) => (g && Object.prototype.hasOwnProperty.call(DESC, g)) ? DESC[g] : null;

  function isGeneSelect(sel) {
    if (/gene/i.test(sel.id || "") || /gene/i.test(sel.name || "")) return true;
    let hit = 0; const opts = sel.options || [];
    for (let i = 0; i < opts.length && i < 40; i++) if (desc(opts[i].value)) { hit++; if (hit >= 3) return true; }
    return false;
  }
  function syncSelect(sel) {
    const apply = () => { const d = desc(sel.value); sel.title = d || ""; };
    apply();
    if (!sel._giBound) { sel._giBound = true; sel.addEventListener("change", apply); }
  }
  // tag ONE element (idempotent; never clobbers a richer existing title, e.g. a stats tooltip)
  function tagEl(el) {
    if (!el || el.nodeType !== 1 || el._giDone) return;
    if (el.hasAttribute("data-gene") || el.hasAttribute("data-g")) {
      el._giDone = 1; if (!el.title) { const d = desc(el.getAttribute("data-gene") || el.getAttribute("data-g")); if (d) el.title = d; } return;
    }
    if (el.tagName === "OPTION") { el._giDone = 1; const d = desc(el.value); if (d && !el.title) el.title = d; return; }
    if (/^(SPAN|B|STRONG|A|TD|LI)$/.test(el.tagName) && !el.children.length && !el.title) {
      el._giDone = 1; const t = el.textContent.trim(); if (t.length <= 18 && desc(t)) el.title = desc(t);
    }
  }
  function tagRoot(root) {
    if (!root || root.nodeType !== 1 && root.nodeType !== 9) return;
    if (root.nodeType === 1) tagEl(root);
    if (root.querySelectorAll) {
      root.querySelectorAll("[data-gene],[data-g],option,span,b,strong,a,td,li").forEach(tagEl);
      root.querySelectorAll("select").forEach((sel) => { if (isGeneSelect(sel)) syncSelect(sel); });
    }
    if (root.tagName === "SELECT" && isGeneSelect(root)) syncSelect(root);
  }

  let queued = false; const pending = [];
  function flush() { queued = false; pending.splice(0).forEach(tagRoot); }
  function schedule(node) { pending.push(node); if (!queued) { queued = true; requestAnimationFrame(flush); } }

  function start() {
    tagRoot(document);
    const obs = new MutationObserver((muts) => { for (const m of muts) m.addedNodes.forEach((n) => { if (n.nodeType === 1) schedule(n); }); });
    obs.observe(document.body, { childList: true, subtree: true });
    setInterval(() => document.querySelectorAll("select").forEach((s) => { if (isGeneSelect(s)) syncSelect(s); }), 1500);
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", start);
  else start();

  return { desc, DESC, tag: tagRoot };
})();
